#language:pt
Funcionalidade: Cadastro de pessoas

  #Cadastro completo corretamente ~ Fluxo positivo
  @Teste
  Cenario: Deve salvar nova pessoa no sistema com todos os dados preenchidos corretamente
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa
    E  finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  #Tabela: pessoa / Campo: codigo BIGINT GENERATED BY DEFAULT AS SEQUENCE pessoa_id_seq PRIMARY KEY
  @Teste
  Cenário: Deve ser possivel salvar pessoa com campo CODIGO inserido manualmente
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados para campo CODIGO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenário: Deve ser possivel salvar pessoa com campo CODIGO inserido manualmente para valor nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo CODIGO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  #Tabela: pessoa / Campo: nome VARCHAR(80) NOT NULL
  @Teste
  Cenário: Deve ser possível salvar pessoa com campo NOME vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo NOME em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenário: Não deve ser possível salvar pessoa com campo NOME nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo NOME em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo NOME maior que 80 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 80 caracteres para campo NOME em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  @Teste
  Cenario: Não deve ser possível salvar pessoa sem envio de campo NOME em corpo de requisição
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados sem NOME em corpo de requisicao
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: pessoa / Campo: cpf VARCHAR(11) NOT NULL
  @Teste
  Cenario: Deve ser possível salvar pessoa com campo CPF vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo CPF em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo CPF nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo CPF em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo CPF maior que 11 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 11 caracterses para campo CPF em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  @Teste
  Cenario: Não deve ser possivel salvar pessoa sem envio de campo CPF em corpo de requisição
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados sem CPF em corpo de requisicao
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: endereco / Campo: logradouro VARCHAR(255)
  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.LOGRADOURO vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo LOGRADOURO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.LOGRADOURO nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo LOGRADOURO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: ão ser possível salvar pessoa com campo ENDERECOS.LOGRADOURO maior que 255 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 255 caracteres para campo LOGRADOURO em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: endereco / Campo: numero INT
  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.NUMERO nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo NUMERO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possivel salvar pessoa sem envio de ENDERECOS.NUMERO em corpo de requisição
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos sem uso de tag endereco.numero
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  #Tabela: endereco / Campo: complemento VARCHAR(255)
  @Teste
  Cenario: Deve ser possivel salvar pessoa com campo ENDERECOS.COMPLEMENTO vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo COMPLEMENTO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.COMPLEMENTO nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo COMPLEMENTO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo ENDERECOS.COMPLEMENTO maior que 255 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 255 caracteres para campo COMPLEMENTO em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: endereco / Campo: bairro VARCHAR(255)
  @Teste
  Cenario: Deve ser possivel salvar pessoa com campo ENDERECOS.BAIRRO vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo BAIRRO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.BAIRRO nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo BAIRRO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo ENDERECOS.BAIRRO maior que 255 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 255 caracteres para campo BAIRRO em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: endereco / Campo: cidade VARCHAR(255)
  @Teste
  Cenario: Deve ser possivel salvar pessoa com campo ENDERECOS.CIDADE vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo CIDADE em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.CIDADE nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo CIDADE em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo ENDERECOS.CIDADE maior que 255 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 255 caracteres para campo CIDADE em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: endereco / Campo: estado VARCHAR(2)
  @Teste
  Cenario: Deve ser possivel salvar pessoa com campo ENDERECOS.ESTADO vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo ESTADO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possível salvar pessoa com campo ENDERECOS.ESTADO nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo ESTADO em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo ENDERECOS.ESTADO maior que 2 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 2 caracteres para campo ESTADO em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: telefone / Campo: ddd VARCHAR(2) NOT NULL
  @Teste
  Cenario: Deve ser possivel salvar pessoa com campo TELEFONES.DDD vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo DDD em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo TELEFONES.DDD nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo DDD em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo TELEFONES.DDD maior que 2 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 2 caracteres para campo DDD em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  #Tabela: telefone / Campo: numero VARCHAR(9) NOT NULL
  @Teste
  Cenario: Deve ser possivel salvar pessoa com campo TELEFONES.NUMERO vazio
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado vazio para campo TELEFONE em cadastro
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo TELEFONES.NUMERO nulo
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado nulo para campo TELEFONE em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  @Teste
  Cenario: Não deve ser possível salvar pessoa com campo TELEFONES.NUMERO maior que 9 caracteres
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dado maior que 9 caracteres para campo TELEFONE em cadastro
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado por erro em sintaxe SQL

  ################################################################################################
  @Teste
  Cenario: Não deve ser possível salvar duas pessoas com o mesmo CPF
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa
    E finalizar envio de informacoes
    E o cadastro deve ser efetuado com sucesso
    E que preciso cadastrar uma nova pessoa
    E inserir dados corretos para cadastro de pessoa com mesmo CPF
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado para CPF já cadastrado

  @Teste
  Cenario: Não deve ser possível salvar duas pessoas com o mesmo telefone
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa
    E finalizar envio de informacoes
    E o cadastro deve ser efetuado com sucesso
    E que preciso cadastrar uma nova pessoa
    E inserir dados corretos para cadastro de pessoa com mesmo Telefone completo
    E finalizar envio de informacoes
    Então o cadastro não deve ser efetuado para Telefone completo já cadastrado

  @Teste
  Cenario: Deve ser possível salvar duas pessoas com o mesmo TELEFONES.DDD mas TELEFONES.NUMERO diferentes
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa
    E finalizar envio de informacoes
    E o cadastro deve ser efetuado com sucesso
    E que preciso cadastrar uma nova pessoa
    E inserir dados corretos para cadastro de pessoa com mesmo DDD e telefone diferente
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Deve ser possível salvar duas pessoas com o mesmo TELEFONES.NUMERO mas TELEFONES.DDD diferentes
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa
    E finalizar envio de informacoes
    E o cadastro deve ser efetuado com sucesso
    E que preciso cadastrar uma nova pessoa
    E inserir dados corretos para cadastro de pessoa com mesmo telefone e ddd diferente
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Cadastro de pessoa com mais endereços
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa com mais enderecos
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

  @Teste
  Cenario: Cadastro de pessoa com mais telefones
    Dado que preciso cadastrar uma nova pessoa
    Quando inserir dados corretos para cadastro de pessoa com mais telefones
    E finalizar envio de informacoes
    Então o cadastro deve ser efetuado com sucesso

